# add user specific settings
---
- name: Ensure group "microk8s" exists
  become: yes
  ansible.builtin.group:
    name: microk8s
    state: present

- name: Remove the user 'johnd'
  become: yes
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    state: present
    groups: microk8s
    append: true

- name: Create .kube folder for the user
  become_user: '{{ ansible_user }}'
  file:
    path: ~/.kube
    state: directory
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: 0750
  loop_control:
    loop_var: user
    label: '{{ ansible_user }}'