# add user specific settings
---
- name: Ensure group "microk8s" exists
  become: yes
  ansible.builtin.group:
    name: microk8s
    state: present

- name: add user to group
  become: yes
  command: "usermod -a -G microk8s {{ ansible_user }}"
  changed_when: true
  loop_control:
    loop_var: user
    label: '{{ ansible_user }}'

- name: Create .kube folder for the user
  become_user: '{{ ansible_user }}'
  file:
    path: ~/.kube
    state: directory
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: 0750
  loop_control:
    loop_var: user
    label: '{{ ansible_user }}'