# add user specific settings
---
- name: add user to group
  become: yes
  command: "usermod -a -G microk8s {{ ansible_user }}"
  changed_when: true
  loop_control:
    loop_var: user
    label: '{{ ansible_user }}'

- name: Create .kube folder for the user
  become_user: '{{ ansible_user }}'
  file:
    path: ~/.kube
    state: directory
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: 0750
  loop_control:
    loop_var: user
    label: '{{ ansible_user }}'

- name: create kubectl config
  command: "/snap/bin/microk8s.config > /home/{{ ansible_user }}/.kube/config"
  loop_control:
    loop_var: user
    label: '{{ ansible_user }}'