# add user specific settings
---
- name: add user to group
  become: yes
  command: "usermod -a -G microk8s {{ ansible_user }}"
  changed_when: true
  loop_control:
    loop_var: user
    label: '{{ ansible_user }}'

- name: Create .kube folder for the user
  become_user: '{{ ansible_user }}'
  file:
    path: ~/.kube
    state: directory
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: 0750
  loop_control:
    loop_var: user
    label: '{{ ansible_user }}'

- name: create kubectl config
  changed_when: true
  command: "microk8s.config > /home/{{ ansible_user }}/.kube/config"
  loop_control:
    loop_var: user
    label: '{{ ansible_user }}'

- name: reaffirm permission on files
  become: yes
  file:
    path: ~/.kube
    state: directory
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    recurse: yes
    mode: 0750
  loop_control:
    loop_var: user
    label: '{{ ansible_user }}'

- name: add helm repository to user
  command: "helm repo add {{ item.1.name }} {{ item.1.url }}"
  changed_when: true
  with_nested:
    - "{{ ansible_user }}"
    - "{{ helm3_repositories }}"
  when: microk8s_plugins.helm3

- name: update helm repos
  command: "helm repo update"
  changed_when: true
  loop_control:
    loop_var: user
    label: '{{ ansible_user }}'
  when: microk8s_plugins.helm3
