---
- name: Add another bin dir to system-wide $PATH.
  copy:
    dest: /etc/profile.d/custom-path.sh
    content: 'PATH=$PATH:/snap/bin'

- import_tasks: install.yml

- name: configure single node addons
  include_tasks: addons.yml
  when: not microk8s_enable_HA

- name: configure High Availability
  include_tasks: configure-HA.yml
  when: "microk8s_enable_HA"

- name: configure workers
  include_tasks: configure-WORKERS.yml
  when: "groups[microk8s_group_WORKERS] is defined and groups[microk8s_group_WORKERS]|length>0"
